//===-- RV32IInstPrinter.h - Convert RV32I MCInst to assembly syntax ----===//
//
// This file contains the declaration of the RV32IInstPrinter class,
// which is used to print RV32I MCInst to a .s file.
//
//===----------------------------------------------------------------------===//

#ifndef LLVM_LIB_TARGET_RV32I_MCTARGETDESC_RV32IINSTPRINTER_H
#define LLVM_LIB_TARGET_RV32I_MCTARGETDESC_RV32IINSTPRINTER_H

#include "llvm/MC/MCInstPrinter.h"

namespace llvm {

/// RV32IInstPrinter:
/// Prints `MCInst`s as human-readable RISC-V assembly language text.
class RV32IInstPrinter : public MCInstPrinter {
public:
  RV32IInstPrinter(const MCAsmInfo &MAI, const MCInstrInfo &MII,
                   const MCRegisterInfo &MRI)
      : MCInstPrinter(MAI, MII, MRI) {}

  // Autogenerated by tblgen.
  std::pair<const char *, uint64_t> getMnemonic(const MCInst &MI) const override;
  void printInstruction(const MCInst *MI, uint64_t Address,
                        const MCSubtargetInfo &STI, raw_ostream &O);
  bool printAliasInstr(const MCInst *MI, uint64_t Address,
                       const MCSubtargetInfo &STI, raw_ostream &O);
  void printCustomAliasOperand(const MCInst *MI, uint64_t Address,
                               unsigned OpIdx, unsigned PrintMethodIdx,
                               const MCSubtargetInfo &STI, raw_ostream &O);
  static const char *getRegisterName(MCRegister RegNo);

  /// printRegName: Prints the name of a register (e.g., `x10` or `a0`).
  void printRegName(raw_ostream &OS, MCRegister RegNo) override;
  /// printInst: The main entry point for printing an instruction.
  void printInst(const MCInst *MI, uint64_t Address, StringRef Annot,
                 const MCSubtargetInfo &STI, raw_ostream &O) override;

  /// printOperand: Prints a generic operand (register, immediate, or symbol).
  void printOperand(const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI,
                    raw_ostream &O);
                    
  void printUImm20Operand(const MCInst *MI, unsigned OpNo,
                          const MCSubtargetInfo &STI, raw_ostream &O);
                          
  void printSimm12Operand(const MCInst *MI, unsigned OpNo,
                          const MCSubtargetInfo &STI, raw_ostream &O);
                    
  /// printBranchOperand: Prints a branch target (handles offset calculations).
  void printBranchOperand(const MCInst *MI, unsigned OpNo,
                          const MCSubtargetInfo &STI, raw_ostream &O);
};

} // end namespace llvm

#endif // LLVM_LIB_TARGET_RV32I_MCTARGETDESC_RV32IINSTPRINTER_H
