//===-- RV32IMCCodeEmitter.cpp - Convert RV32I code to machine code -------===//
//
// This file implements the `MCCodeEmitter` interface. 
// It is responsible for taking an `MCInst` (like `ADD X10, X11, X12`) and 
// converting it into the actual 32-bit binary encoding (e.g., `0x00C58533`) 
// that the CPU will execute.
//
// It relies heavily on the `getBinaryCodeForInstr` function, which is 
// auto-generated by TableGen from our `.td` instruction format definitions!
//
//===----------------------------------------------------------------------===//

#include "RV32IMCTargetDesc.h"
#include "llvm/MC/MCCodeEmitter.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/EndianStream.h"

using namespace llvm;

#define DEBUG_TYPE "mccodeemitter"

namespace {
class RV32IMCCodeEmitter : public MCCodeEmitter {
  const MCInstrInfo &MCII;
  MCContext &Ctx;

public:
  RV32IMCCodeEmitter(const MCInstrInfo &mcii, MCContext &ctx)
      : MCII(mcii), Ctx(ctx) {}
  ~RV32IMCCodeEmitter() override {}

  /// encodeInstruction:
  /// The main entry point. Takes an `MCInst` and appends its encoded bytes 
  /// into the output buffer `CB`.
  void encodeInstruction(const MCInst &MI, SmallVectorImpl<char> &CB,
                         SmallVectorImpl<MCFixup> &Fixups,
                         const MCSubtargetInfo &STI) const override;

  /// getBinaryCodeForInstr:
  /// Auto-generated by TableGen. Returns the 32-bit integer encoding of the instruction.
  uint64_t getBinaryCodeForInstr(const MCInst &MI,
                                 SmallVectorImpl<MCFixup> &Fixups,
                                 const MCSubtargetInfo &STI) const;

  unsigned getMachineOpValue(const MCInst &MI, const MCOperand &MO,
                             SmallVectorImpl<MCFixup> &Fixups,
                             const MCSubtargetInfo &STI) const;

  unsigned getBranchTargetOpValue(const MCInst &MI, unsigned OpNo,
                                  SmallVectorImpl<MCFixup> &Fixups,
                                  const MCSubtargetInfo &STI) const;
};
} // end anonymous namespace

MCCodeEmitter *llvm::createRV32IMCCodeEmitter(const MCInstrInfo &MCII,
                                              MCContext &Ctx) {
  return new RV32IMCCodeEmitter(MCII, Ctx);
}

void RV32IMCCodeEmitter::encodeInstruction(const MCInst &MI,
                                           SmallVectorImpl<char> &CB,
                                           SmallVectorImpl<MCFixup> &Fixups,
                                           const MCSubtargetInfo &STI) const {
  uint32_t Bits = getBinaryCodeForInstr(MI, Fixups, STI);
  support::endian::write(CB, Bits, llvm::endianness::little);
}

unsigned RV32IMCCodeEmitter::getMachineOpValue(const MCInst &MI,
                                               const MCOperand &MO,
                                               SmallVectorImpl<MCFixup> &Fixups,
                                               const MCSubtargetInfo &STI) const {
  if (MO.isReg())
    return Ctx.getRegisterInfo()->getEncodingValue(MO.getReg());
  if (MO.isImm())
    return static_cast<unsigned>(MO.getImm());
  llvm_unreachable("Unhandled expression!");
  return 0;
}

unsigned RV32IMCCodeEmitter::getBranchTargetOpValue(const MCInst &MI, unsigned OpNo,
                                                    SmallVectorImpl<MCFixup> &Fixups,
                                                    const MCSubtargetInfo &STI) const {
  const MCOperand &MO = MI.getOperand(OpNo);
  if (MO.isImm())
    return MO.getImm();
  
  // For now, if we emit objects directly, we'd add a fixup here. 
  // Since we only emit assembly text for our tests, we can just return 0.
  // Real RISC-V backend adds fixups like RISCV::fixup_riscv_jal.
  return 0;
}

#include "RV32IGenMCCodeEmitter.inc"
