//===-- RV32IInstPrinter.cpp - Convert RV32I MCInst to assembly syntax ----===//
//
// This file implements the `MCInstPrinter` interface. 
// It relies heavily on the `printInstruction` function, which is 
// auto-generated by TableGen from the `AsmString` fields in our `.td` files!
//
//===----------------------------------------------------------------------===//

#include "RV32IInstPrinter.h"
#include "RV32IMCTargetDesc.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"

using namespace llvm;

#define DEBUG_TYPE "asm-printer"

// Include the auto-generated portion of the assembly writer.
#define PRINT_ALIAS_INSTR
#include "RV32IGenAsmWriter.inc"

void RV32IInstPrinter::printRegName(raw_ostream &O, MCRegister RegNo) {
  O << getRegisterName(RegNo);
}

/// printInst:
/// First, we try to print an alias (e.g., `ret` instead of `jalr x0, 0(ra)`).
/// If it's not an alias, we just print the raw instruction using TableGen's 
/// generated `printInstruction`.
void RV32IInstPrinter::printInst(const MCInst *MI, uint64_t Address,
                                 StringRef Annot, const MCSubtargetInfo &STI,
                                 raw_ostream &O) {
  if (!printAliasInstr(MI, Address, STI, O))
    printInstruction(MI, Address, STI, O);
  printAnnotation(O, Annot);
}

/// printOperand:
/// Prints a generic operand. We check if it's a register (print its name), 
/// an immediate (print its integer value), or an expression (like a global 
/// variable symbol).
void RV32IInstPrinter::printOperand(const MCInst *MI, unsigned OpNo,
                                    const MCSubtargetInfo &STI,
                                    raw_ostream &O) {
  const MCOperand &MO = MI->getOperand(OpNo);

  if (MO.isReg()) {
    printRegName(O, MO.getReg());
    return;
  }

  if (MO.isImm()) {
    O << MO.getImm();
    return;
  }

  if (MO.isExpr()) {
    MAI.printExpr(O, *MO.getExpr());
    return;
  }

  llvm_unreachable("Unknown operand");
}

void RV32IInstPrinter::printUImm20Operand(const MCInst *MI, unsigned OpNo,
                                          const MCSubtargetInfo &STI,
                                          raw_ostream &O) {
  const MCOperand &MO = MI->getOperand(OpNo);
  if (MO.isExpr()) {
    O << "%hi(";
    MAI.printExpr(O, *MO.getExpr());
    O << ")";
  } else {
    printOperand(MI, OpNo, STI, O);
  }
}

void RV32IInstPrinter::printSimm12Operand(const MCInst *MI, unsigned OpNo,
                                          const MCSubtargetInfo &STI,
                                          raw_ostream &O) {
  const MCOperand &MO = MI->getOperand(OpNo);
  if (MO.isExpr()) {
    O << "%lo(";
    MAI.printExpr(O, *MO.getExpr());
    O << ")";
  } else {
    printOperand(MI, OpNo, STI, O);
  }
}

/// printBranchOperand:
/// Used for B-type and J-type instructions where the immediate is a memory offset.
void RV32IInstPrinter::printBranchOperand(const MCInst *MI, unsigned OpNo,
                                          const MCSubtargetInfo &STI,
                                          raw_ostream &O) {
  const MCOperand &MO = MI->getOperand(OpNo);
  if (MO.isExpr()) {
    MAI.printExpr(O, *MO.getExpr());
  } else if (MO.isImm()) {
    O << MO.getImm();
  } else {
    llvm_unreachable("Unknown branch operand");
  }
}
