//===-- RV32ISelDAGtoDAG.h - A dag to dag inst selector for RV32I -*- C++ -*-===//
//
// Once the intermediate representation (IR) is lowered into a SelectionDAG, 
// we need to translate those generic nodes (like `add`, `sub`, `load`) into 
// actual RV32I machine instructions.
// 
// This file declares the classes responsible for that translation. Most of 
// the logic is auto-generated by TableGen from our `.td` patterns.
//
//===----------------------------------------------------------------------===//

#ifndef LLVM_LIB_TARGET_RV32I_RV32ISELDAGTODAG_H
#define LLVM_LIB_TARGET_RV32I_RV32ISELDAGTODAG_H

#include "RV32I.h"
#include "RV32ITargetMachine.h"
#include "llvm/CodeGen/SelectionDAGISel.h"

namespace llvm {

/// RV32IDAGToDAGISel:
/// This is the core Instruction Selector class. It inherits from SelectionDAGISel 
/// which provides the framework for pattern matching.
class RV32IDAGToDAGISel : public SelectionDAGISel {
public:
  explicit RV32IDAGToDAGISel(RV32ITargetMachine &TM, CodeGenOptLevel OptLevel)
      : SelectionDAGISel(TM, OptLevel) {}

  /// Select:
  /// We can override this function to perform custom instruction selection 
  /// for complex nodes before falling back to TableGen's generated matcher.
  void Select(SDNode *Node) override;

// Include the piece of code auto-generated from our TableGen patterns.
#include "RV32IGenDAGISel.inc"
};

/// RV32IDAGToDAGISelLegacy:
/// In recent versions of LLVM (like 23.0), the pass manager structure changed.
/// `SelectionDAGISel` is no longer a `MachineFunctionPass`. Instead, we use a 
/// "Legacy" wrapper pattern to adapt our ISel class to the old pass manager, 
/// which `TargetPassConfig` still expects.
class RV32IDAGToDAGISelLegacy : public SelectionDAGISelLegacy {
public:
  static char ID;
  explicit RV32IDAGToDAGISelLegacy(RV32ITargetMachine &TM,
                                   CodeGenOptLevel OptLevel);
};

} // namespace llvm

#endif // LLVM_LIB_TARGET_RV32I_RV32ISELDAGTODAG_H
