//===-- RV32ISubtarget.h - Define Subtarget for the RV32I -----*- C++ -*-===//
//
// The Subtarget acts as the central hub for the architecture's specific 
// properties. If we were building a backend that supported different RISC-V 
// extensions (like M for multiply, F for float, etc.), this class would 
// track which extensions are enabled for a given compilation unit.
//
// Even for a simple backend, the Subtarget is crucial because it acts as a 
// container for all the major code generation components: the Instruction Info, 
// Frame Lowering, Target Lowering, and SelectionDAG Info.
//
//===----------------------------------------------------------------------===//

#ifndef LLVM_LIB_TARGET_RV32I_RV32ISUBTARGET_H
#define LLVM_LIB_TARGET_RV32I_RV32ISUBTARGET_H

#include "RV32IFrameLowering.h"
#include "RV32IInstrInfo.h"
#include "RV32ISelLowering.h"
#include "RV32IRegisterInfo.h"
#include "llvm/CodeGen/SelectionDAGTargetInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/Target/TargetMachine.h"

#define GET_SUBTARGETINFO_HEADER
#include "RV32IGenSubtargetInfo.inc"

namespace llvm {
class StringRef;

class RV32ISubtarget : public RV32IGenSubtargetInfo {
  virtual void anchor();

  /// Code Generation Components:
  /// These components handle the heavy lifting for different phases of compilation.
  RV32IInstrInfo InstrInfo;             // Instruction encodings and definitions
  RV32IFrameLowering FrameLowering;     // Stack layout and prologue/epilogue
  RV32ITargetLowering TLInfo;           // Lowering IR and DAG nodes to RV32I nodes
  SelectionDAGTargetInfo TSInfo;        // SelectionDAG heuristics

public:
  /// Constructor: 
  /// Initializes the Subtarget with the specific features requested (like CPU name).
  RV32ISubtarget(const Triple &TT, const StringRef CPU, const StringRef FS,
                 const TargetMachine &TM);

  /// ParseSubtargetFeatures:
  /// This function is automatically generated by TableGen based on `RV32I.td`.
  /// It parses feature flags passed from the command line (e.g., `-mattr=+m`).
  void ParseSubtargetFeatures(StringRef CPU, StringRef TuneCPU, StringRef FS);

  const RV32IInstrInfo *getInstrInfo() const override { return &InstrInfo; }
  const RV32IFrameLowering *getFrameLowering() const override {
    return &FrameLowering;
  }
  const RV32ITargetLowering *getTargetLowering() const override {
    return &TLInfo;
  }
  const RV32IRegisterInfo *getRegisterInfo() const override {
    return &InstrInfo.getRegisterInfo();
  }
  const SelectionDAGTargetInfo *getSelectionDAGInfo() const override {
    return &TSInfo;
  }
};
} // end namespace llvm

#endif // LLVM_LIB_TARGET_RV32I_RV32ISUBTARGET_H
